### PR TITLE
Fix font display on win/chrome

### LINKED ISSUE #7630: Show a message to XP users to enable ClearType?
I've seen a fair amount of users (of older OSes/browsers) complaining the font is unreadable. I dug into [one case recently](http://discussion.theguardian.com/comment-permalink/45289337) and enabling ClearType (on Windows XP) fixed the issue.

It looks like [it's possible to detect font-smoothing support](http://www.useragentman.com/blog/2009/11/29/how-to-detect-font-smoothing-using-javascript/) (which is effectively ClearType enabled on WinXP) – would it be worth doing this and showing a message explaining how to enable it for these users? At the moment it's quite a poor experience for them and makes the site effectively unreadable:

graun_beta_sample_zpsafff80f3

In the last 30 days, traffic from XP was 2,649,303 	unique visitors (2.6%) – this is a lot of people experiencing a pretty ugly type appearance. Can we at least acknowledge it for them?

cc @phamann / @crifmulholland

### PR DESCRIPTION
**Pull request by sndrs**
fixes #7630

Egyptian text below 18px displays badly in chrome on windows where font-smoothing is disabled:

screen shot 2015-01-05 at 16 54 23

This curious hack renders all text that follows the new element smoothly:

screen shot 2015-01-05 at 16 56 15

It's in the DOM by default to avoid layout thrashing on initial load, given this happens mainly on old machines anyway. 

The overhead on more modern machines should be minimal; the vendor-prefix means it will be ignored by non-webkit browsers (and newer chromes that drop support for it, etc), and only on desktops too (both good ideas from @sammorrisdesign :star:).

cc @mattandrews @paperboyo @ironsidevsquincy

### CODE REVIEW

**Comment by sndrs** [comment]
going to move the css to the head - one mo...

**Comment by paperboyo** [comment]
:gem:!

File: common/app/views/main.scala.html [hunk 1]
```diff
@@ -25,6 +25,8 @@
             ("childrens-books-site", metaData.section == "childrens-books-site")))"
         itemscope itemtype="http://schema.org/WebPage">
 
+        <div class="win-chrome-font-fix">@* hack to fix fonts in win/chrome with font-smoothing disabled *@</div>
```
Comment (ironsidevsquincy) [inline common/app/views/main.scala.html]: just chrome, not ff/others? would `win-font-fix` be better?

**Comment by ironsidevsquincy** [comment]
Excellent! :+1:

File: common/app/views/main.scala.html (hunk 1 above)
Comment (sndrs) [inline common/app/views/main.scala.html]: only chrome seems to be affected now - i think all the hinting etc stuff you did has everything else covered?

**Comment by robertberry** [comment]
What a :gift:

File: common/app/views/main.scala.html (hunk 1 above)
Comment (paperboyo) [inline common/app/views/main.scala.html]: As far as I know hinting is not affecting this issue. There is only one instance when hinting fixes horrible rendering - when there is no display driver (graphics acceleration) and Firefox is used (on all Win versions). Apart from that hinting sometimes looks better and sometimes worse but never fixes unreadable font rendering. Screenshots showing different hinting/browser/font smoothing options combinations are on our Win7 test machine.

If there would be similar fix for FF (to force font smoothing when the setting for that is off in Windows) it would be nice to use it (IE completely disregards system font smoothing settings :).
