### PR TITLE
Fix admin pages and offline page in dev environment

### LINKED ISSUE #11100: admin JS is broken locally
Broken by https://github.com/guardian/frontend/pull/11009/files#diff-aef18c02671cecab73288a55f9311a39R25

### PR DESCRIPTION
**Pull request by OliverJAsh**
This was broken in #11109 

Fixes #11100

### CODE REVIEW

File: common/app/dev/DevAssetsController.scala [hunk 1]
```diff
@@ -17,9 +17,7 @@ object DevAssetsController extends Controller with ExecutionContexts {
 
     val hashFile = new File(s"static/hash/$path")
 
-    val resolved = if (Play.isDev && path.startsWith("javascripts")) {
-      new File(s"static/src/$path").toURI.toURL
-    } else if (hashFile.exists()) {
+    val resolved = if (hashFile.exists()) {
       hashFile.toURI.toURL
     } else {
       new File(s"static/src/$path").toURI.toURL
```
Comment (OliverJAsh) [inline common/app/dev/DevAssetsController.scala]: This works for dev.

**Comment by OliverJAsh** [comment]
Ping @rich-nguyen. Any thoughts on this?

**Comment by rich-nguyen** [comment]
makes sense :+1:
