### PR TITLE
Fix: dedup backfill against trails from the same collection

### LINKED ISSUE #25249: Fixed containers including wrong number of cards
Sometimes our editors use a mix of backfills & curations for containers - curated cards go at the top of the container, with the backfill cards taking up the remaining space in the container. 

Annotated Example:
Curated+backfill

Unfortunately there is a bug in this behaviour, specifically when some of the curated content is the same as what is returned in the backfill. 

For example, in the annotation above, there are supposed to be 14 total cards - however there are only 12.

From testing - this only happens when some curated cards are the same as the backfilled ones; therefore we can imagine the logic looks something like:
1. Take the first 14 cards, for example the 3 curated cards & the first 11 backfill cards
2. From that list, we (now) de-duplicate, removing 2 of the backfill cards which are already included in the curated list
3. We render the container, now missing 2 cards

To fix this, we may want to see if we can find & move the de-duplication logic to _before_ the stage where we take the number of cards we want for the container.

From testing this may happen on all fixed containers. Dynamic containers may have this problem too but they are currently rarely used with backfills.

---

Central production set up this test front: https://m.code.dev-theguardian.com/dupeissue

However depending on when this issue is worked on, the curated cards may be 'out of date' and would need to be updated in order to recreate the issue. If you're unsure how to do this contact Gabriel Smith.

On this test front you can also see what the container looks like with all of its cards in place!

### PR DESCRIPTION
**Pull request by bryophyta**
## What does this change?

In the deduping logic for facia-press, it adds the urls from the current collection's `curated` list to the list of urls against which the `backfill` for the current collection is deduped.

Prior to this, backfill trails for a collection were only being checked against the trails which were present in the collections which had been processed earlier on in the deduping process (e.g. earlier on in the page, if the collection is part of a front). So if a trail was present in both the `curated` and `backfill` lists for a collection, but not in any of the prior collections that had been deduped already, then it would not be removed.

Also adds a test case for this scenario.

Closes #25249.

## Screenshots

| Before | After |
| --- | --- |
| image | image |
| Two cards missing from bottom row | The right number of cards, with no duplicates |

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### CODE REVIEW

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala [hunk 1]
```diff
@@ -51,7 +57,10 @@ object PressedCollectionDeduplication {
       collectionV: PressedCollectionVisibility,
   ): PressedCollectionVisibility = {
     // Essentially deduplicate the backfill of collectionV using header values values from accum's elements curated and backfill
-    val accumulatedHeaderURLsForDeduplication: Seq[String] = getHeaderURLsFromCuratedAndBackfilledAtDepth(accum, 10)
+    val accumulatedHeaderURLsForDeduplication: Seq[String] =
```
Comment (ioannakok) [inline facia-press/app/frontpress/PressedCollectionDeduplication.scala:60]: This change makes sense to me but it took me a while to understand the flow. Would it make sense to rename this variable to `headerURLsForDeduplication` as this sequence is no longer constructed only from the accumulator but also from the curated content of the `collectionV`? 

(btw I think I would also rename `collectionV` to just `collection`)

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala [hunk 2]
```diff
@@ -51,7 +57,10 @@ object PressedCollectionDeduplication {
...
+      getHeaderURLsFromCuratedAndBackfilledAtDepth(accum, 10) ++ getHeaderURLsFromTrailsList(
```
Comment (ioannakok) [inline facia-press/app/frontpress/PressedCollectionDeduplication.scala:61]: Do you know why we're taking 10?

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala [hunk 3]
```diff
@@ -51,7 +57,10 @@ object PressedCollectionDeduplication {
       collectionV: PressedCollectionVisibility,
   ): PressedCollectionVisibility = {
     // Essentially deduplicate the backfill of collectionV using header values values from accum's elements curated and backfill
```
Comment (OllysCoding) [inline facia-press/app/frontpress/PressedCollectionDeduplication.scala:59]: Could we expand this comment somehow to explain that `getHeaderURLsFromCuratedAndBackfilledAtDepth(accum, 10)` fetches headerUrls from _previous_ containers, and `getHeaderURLsFromTrailsList(collectionV.pressedCollection.curated)` is the curated cards for the current container? This might help the readability a bit?

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala [hunk 4]
```diff
@@ -51,7 +57,10 @@ object PressedCollectionDeduplication {
...
-    val accumulatedHeaderURLsForDeduplication: Seq[String] = getHeaderURLsFromCuratedAndBackfilledAtDepth(accum, 10)
+    val accumulatedHeaderURLsForDeduplication: Seq[String] =
+      getHeaderURLsFromCuratedAndBackfilledAtDepth(accum, 10) ++ getHeaderURLsFromTrailsList(
+        collectionV.pressedCollection.curated,
```
Comment (OllysCoding) [inline facia-press/app/frontpress/PressedCollectionDeduplication.scala:62]: I think this is my inexperience with this code, but does this function (`deduplicateCollectionAgainstAccumulator`) de-duplicate only the backfill, or the backfill & the curated content?

**Review by OllysCoding — COMMENTED** [review]
This is some great work! I'm super happy to see some testing in here as well :) There is perhaps some work we can do to improve the clarity of how this deduplication works - but its worth nothing that I think most of it comes from the existing complexity of this file. 

Great work Pete!

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 2 above)
Comment (bryophyta) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala:61]: I'm not actually sure, although my guess would be that it's because a collection can have way more backfill cards than would ever be displayed in the main container, but we don't want to remove a card from later containers just because it's in the  'show more' section of a container above. With 10 being an approximation of the max number of cards that would be displayed in the main container?

If this is the purpose then I suspect that we could refactor it, but I thought I should keep this PR targeted and maybe come back to some of these  other  issues later on?

The comments  in the file hint at a  planned  refactor  of the  visibility  logic as well, which doesn't look like it was  every  finished, so it  could be good to see if we can find  any more context on that?

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 3 above)
Comment (bryophyta) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala:59]: sounds good!

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 4 above)
Comment (bryophyta) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala:62]: the existing comments and test cases seem to suggest that cards will only ever be removed from backfill, not curated. I'm pretty sure that when I was working on this last week I saw that that is how it works, but can't remember the details. I'll look again when I revisit it 👍

**Review by OllysCoding — APPROVED** [review]
+1 Looks great :)

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 1 above)
Comment (bryophyta) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala]: Thanks for this! I've updated the name of the `headersURLs...` variable as you suggested. 

I can see the case for renaming `collectionV`, but it seems like it was quite a conscious choice to highlight that it's a `pressedCollectionVisibility` (also in the `pCVs` variable) and I'm not 100% sure I understand the implications of that,  so I'm inclined to leave it for now  until we have a clearer understanding of this bit of functionality?

**Review by ioannakok — APPROVED** [review]
💯 what @OllysCoding says! Great work!

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 2 above)
Comment (ioannakok) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala:66]: Yeah absolutely not in the scope of this PR! You've done a great job already at making things simpler!

File: facia-press/app/frontpress/PressedCollectionDeduplication.scala (hunk 1 above)
Comment (ioannakok) [reply facia-press/app/frontpress/PressedCollectionDeduplication.scala]: Yeah that's perfectly fine. Like Olly said there is an existing complexity in how deduplication works but I think your work was a really good opportunity for us to think / understand a bit better about some parts of this logic.
