### PR TITLE
Fix search for ad block users

### LINKED ISSUE #10030: Sticky nav: search misbehaving
Hello,

Chrome 44, FF 39 on Win 7; AdBlock Plus default installation; IE11.

In Chrome with AdBlock active, search results are cut off after initial scrolling even one line down, like so (and there is **no way** to get them back):

search cut off chrome with adblock

With AdBlock switched off, everything works as expected.

~~In FF, with or without AdBlock Plus, one can not scroll the search results at all (e.g. to get to their pagination), instead, the content area scrolls.~~

In IE11 search bar hides under the ad after initial scroll (but otherwise everything works as expected):

search ie

Regards
Mateusz

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes #10030 

A good proportion of user feedback is users who are using an ad blocker complaining that search doesn't work. It's a trivial fix.

/cc @Calanthe @uplne @paperboyo

### CODE REVIEW

File: static/src/javascripts/projects/common/modules/navigation/sticky.js [hunk 1]
```diff
@@ -437,7 +437,7 @@ define([
                 // Header is not slim yet
                 this.$els.header.removeClass('l-header--is-slim');
                 this.$els.header.css({
-                    position:  'static',
+                    position:  'relative',
```
Comment (OliverJAsh) [inline static/src/javascripts/projects/common/modules/navigation/sticky.js]: The issue was that the `z-index` wasn't being applied because it is only honoured for `relative` and `absolute` positioned elements.

I noticed there were other z-indexes set by the sticky nav along with position static. I don't know what the purpose of these is, as they will not be honoured. Any ideas @Calanthe @uplne?

**Comment by paperboyo** [comment]
Thanks for that, @OliverJAsh! I remember vaguely some issue around thrashers and z-indexes... Oh, yes, that (luckily, git search is working correctly ;-) ): https://github.com/guardian/frontend/issues/9647

**Comment by paperboyo** [comment]
Apparently, my head doesn't, though... it was about sticky nav (which has its own share of search-related problems...) sorry...

**Comment by gtrufitt** [comment]
:+1:

**Comment by sndrs** [comment]
nice! :+1:

**Comment by sammorrisdesign** [comment]
:+1:

File: static/src/javascripts/projects/common/modules/navigation/sticky.js (hunk 1 above)
Comment (Calanthe) [inline static/src/javascripts/projects/common/modules/navigation/sticky.js]: Tbh I don't remember why it is `static`. Big thanks for noticing and fixing it!

**Comment by johnduffell** [comment]
ship it!

**Comment by sammorrisdesign** [comment]
:+1:

**Comment by sammorrisdesign** [comment]
:+1:
