### PR TITLE
Add more logging to Deeply Read & reduce bugs

### LINKED ISSUE #11066: Investigate deeply read dissappearing
Deeply read disappeared for a while. 

Turns out this is because of a bug where we unintentionally fail the entire query even when only one item fails to load from CAPI. This means the recovery time is much higher than it should be when things go wrong (e.g. circuit breaker kicks in) because ALL the articles need to come back with 200 responses before we return deeply read content.

### PR DESCRIPTION
**Pull request by mxdvl**
## What is the value of this and can you measure success?

We recently stopped receiving data for Deeply Read, but our current logging was insufficient to correctly identify the source of the error, so we add more logging to help future developers investigate where things may have gone awry.

We also [may have fixed a bug](https://github.com/guardian/dotcom-rendering/issues/11066) by flattening, rather than getting, where `Seq[Option[Trail]]` was turned into `Seq[Trail]`. It is possible that previously any issue in querying CAPI for any of the trail would result in the entire Future to fail.

## What does this change?

Add logging for:
- a `DeeplyReadAgent.refresh()` failure
- a `ophanApi.getDeeplyRead(edition) ` failure
- the edition for which items are fetched
- the final number of items update in the map

Change the `trailFromCapiResponse.map(_.get)` into `trailFromCapiResponse.map(_.flatten)` to prevent errors being thrown!

## Screenshots

N/A

## Checklist

- [ ] Tested locally, and on CODE if necessary
- [X] Will not break dotcom-rendering
- [X] Will not break our database – if updating CAPI, [updated and committed the database files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)
- [X] Meets our accessibility [standards](https://github.com/guardian/recommendations/blob/e647ef695199ea3116ea20d827ef0f1364270a39/accessibility.md)
  - [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
  - [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#Keyboard)
  - [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#colour)

### CODE REVIEW

File: common/app/agents/DeeplyReadAgent.scala [hunk 1]
```diff
@@ -33,40 +33,54 @@ class DeeplyReadAgent(contentApiClient: ContentApiClient, ophanApi: OphanApi) ex
...
+                        log.error(s"Error retrieving CAPI data for Deeply Read item: ${path}. ${e.getMessage}")
+                        None
                     }
-                  }
-                  .recover {
-                    case NonFatal(e) =>
-                      log.error(s"Error retrieving CAPI data for Deeply Read item: ${path}. ${e.getMessage}")
-                      None
-                  }
-                trailFromCapiResponse.map(_.get)
```
Comment (mxdvl) [inline common/app/agents/DeeplyReadAgent.scala:63]: Thanks to @jonathonherbert and @alinaboghiu for confirming my hunch that this was a real issue!

**Review by sunnyclimber456 — APPROVED** [review]
Nice!! PR title a bit out of sync with the changes but not a big deal!

File: common/app/agents/DeeplyReadAgent.scala [hunk 2]
```diff
@@ -33,40 +33,54 @@ class DeeplyReadAgent(contentApiClient: ContentApiClient, ophanApi: OphanApi) ex
...
+            log.error(s"Failed to fetch Deeply Read items for ${edition.displayName}. ${e.getMessage()}")
+            (edition, Seq.empty)
+          }
       })
       .map(trailsList => {
-        val map = Edition.allEditions.zip(trailsList).toMap
+        val map = trailsList.toMap
+        for {
+          (edition, list) <- map
+        } yield log.info(s"Deeply Read in ${edition.displayName}: ${list.map(_.url).toString()}")
```
Comment (mxdvl) [inline common/app/agents/DeeplyReadAgent.scala:83]: This is working nicely:

image
