### PR TITLE
Fixing Show More Bug

### LINKED ISSUE #10243: Links to 'more' articles on football front broken
When you are on a tag page and select the 'More' button, the articles that then appear aren't selectable as links to that piece of content.

Reproduced on Chrome & Safari

### PR DESCRIPTION
**Pull request by NataliaLKB**
This should fix  #10243.

### CODE REVIEW

File: static/src/javascripts/bootstraps/football.js [hunk 1]
```diff
@@ -264,7 +264,7 @@ define([
         });
 
         // Binding
-        bean.on(document.body, 'click', '.js-show-more', function (e) {
+        bean.on(document.body, 'click', '.matches-nav .js-show-more', function (e) {
```
Comment (uplne) [inline static/src/javascripts/bootstraps/football.js]: So is the issue here that we have more listeners for '.js-show-more' somewhere else and that's what is causing buggy behaviour?

If that's the case then I would suggest to change the name of js hook for this feature instead of increasing specificity this way as there is no indication for `.matches-nav` class that it has other function than just styling thus removing/changing it will return this bug or make show more functionality stop working.

**Comment by NataliaLKB** [comment]
@uplne I completely agree. After a bit more digging certainly the class `football-matches__show-more` is the correct class to attach this listener to. That class is only used in the situation where you need this api call. Unlike `js-show-more` with is used a lot.

File: static/src/javascripts/bootstraps/football.js [hunk 2]
```diff
@@ -250,7 +250,7 @@ define([
         });
 
         // Binding
-        bean.on(document.body, 'click', '.js-show-more', function (e) {
+        bean.on(document.body, 'click', '.football-matches__show-more', function (e) {
```
Comment (sndrs) [inline static/src/javascripts/bootstraps/football.js]: need to use `.js-` prefix on classes for js

Comment (NataliaLKB) [inline static/src/javascripts/bootstraps/football.js]: Good to know! Will update with that change soon.

**Comment by NataliaLKB** [comment]
@sndrs Let me know if this is better!

**Comment by sndrs** [comment]
do they need to be the same name?

**Comment by NataliaLKB** [comment]
Haha thanks @sndrs! Good catch!

**Comment by sndrs** [comment]
:) :+1:

**Comment by NataliaLKB** [comment]
Passed all tests. Merging!
