### PR TITLE
Fix #12828

### LINKED ISSUE #12828: Football results: More button doesn't keep competition or tag filter
# ISSUE
When looking at Football results for a specific competitions (ex: https://www.theguardian.com/football/championsleague/results ) or specific team (ex: https://www.theguardian.com/football/leicestercity/results), clicking the blue 'More' button loads all previous results rather than the previous results related to the filtered competition or team.

## Steps to Reproduce
1. Go to https://www.theguardian.com/football/championsleague/results
2. Scroll down and click on the blue 'More' button

## Actual Results
Previous results from all leagues are displayed

## Expected Results
Only previous results for the 'Champion's League' are displayed

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

Fix #12828:
- Add 'more' endpoints for football tag results
- Refactor ResultsController to avoid duplication of code
- Add tests for ResultsController
## What is the value of this and can you measure success?

One can go through paginated results when a competition or team filter is selected
## Does this affect other platforms - Amp, Apps, etc?

No
## Request for comment

@JustinPinner

### CODE REVIEW

File: sport/app/football/controllers/ResultsController.scala [hunk 1]
```diff
@@ -2,70 +2,81 @@ package football.controllers
...
-    renderAllResults(createDate(year, month, day))
+  private def competitionOrTeam(tag: String): Option[Either[Competition, FootballTeam]] = {
+    lookupCompetition(tag).map(Left(_))
+      .orElse(lookupTeam(tag).map(Right(_)))
+  }
 
-  def allResultsJson() = allResults()
-  def allResults(): Action[AnyContent] =
-    renderAllResults(LocalDate.now(Edition.defaultEdition.timezone))
+  private def byType[A](ifAll: => A)(ifCompetition: Competition => A)(ifTeam: FootballTeam => A)(tag: Option[String]): Option[A] = {
```
Comment (TBonnin) [inline sport/app/football/controllers/ResultsController.scala]: I don't really like this method name but I couldn't find something better. Suggestion welcome :)

File: sport/test/football/model/ResultsListTest.scala [hunk 2]
```diff
@@ -145,7 +145,7 @@ import test.ConfiguredTestSuite
       matchDates should equal(matchDates.sortWith((match1Date, match2Date) => match1Date.isAfter(match2Date)))
     }
 
-    "should only show fixtures" in {
+    "should only show results" in {
```
Comment (TBonnin) [inline sport/test/football/model/ResultsListTest.scala]: A copy/paste leftover I guess :P

File: sport/app/football/controllers/ResultsController.scala (hunk 1 above)
Comment (JustinPinner) [inline sport/app/football/controllers/ResultsController.scala]: I know what you mean re. the name of this, but I'm not sure how it could be expressed more clearly. `byCategory`? `byFilter`? `withFilter`?

**Comment by JustinPinner** [comment]
I think this looks ok. It took a few looks to _get it_, but it seems sane! 👍
