### PR TITLE
Use stage `LOCALTEST` for running tests locally

### LINKED ISSUE #26972: Running tests locally doesn't create missing database files
Frontend uses database files to mock responses to network calls. These are stored in [`data/database`](https://github.com/guardian/frontend/tree/main/data/database).

When a network call is changed, the database files should be updated/created when the tests are run. However:

- [this does not happen if the `stage` is `DEVINFRA`](https://github.com/guardian/frontend/blob/274f5041c8a8f958827d73a8389e61cdc435681e/common/test/recorder/HttpRecorder.scala#L39)
- [we always run tests with `stage=DEVINFRA`](https://github.com/guardian/frontend/blob/main/project/ProjectSettings.scala#L80) (since https://github.com/guardian/frontend/pull/26058) 

This means the tests will fail, instead of creating the necessary database files!

### PR DESCRIPTION
**Pull request by sunnyclimber456**
Frontend has the concept of a `DEVINFRA` stage which *sort of* means "CI environment". Setting this stage has the following behaviour:

- Mocks configuration with a local file, instead of resolving configuration from AWS Parameter Store. This means running tests does not require AWS Credentials
  - Desirable for running tests in CI and locally
- Fails tests where the database of mocked request responses is out of date, instead of generating database updates that can be committed.
  - Desirable in CI, but not locally. We want to generate the files when we run the tests locally so we can commit them as part of the PR

Since #26058 we have been running all tests (in CI and locally) with stage `DEVINFRA` but this results in issues like #26972.

This change:

- introduces a new stage `LOCALTEST` which is used when running tests on a developer machine
  - this stage will use the same mocked configuration as `DEVINFRA`, so AWS credentials are not required
  - this stage will create any necessary database files/updates instead of failing the tests
  - `LOCALTEST` is selected when running tests locally, but not in `CI` where we want to continue using `DEVINFRA`
- `DEVINFRA` continues to behave as before

Closes #26972

### CODE REVIEW

**Review by cemms1 — APPROVED** [review]
👏 so needed! This is great!

Couple of readability suggestions but looks fab

File: project/ProjectSettings.scala [hunk 1]
```diff
@@ -77,7 +81,7 @@ object ProjectSettings {
     Test / javaOptions += "-XX:+UseConcMarkSweepGC",
     Test / javaOptions += "-XX:ReservedCodeCacheSize=128m",
     Test / baseDirectory := file("."),
-    Test / envVars := Map("STAGE" -> "DEVINFRA"),
+    Test / envVars := getTestStage(sys.env.get("CI").getOrElse("false") == "true"),
```
[the remark this answers is not in the document]
Comment (georgeblahblah) [reply project/ProjectSettings.scala]: I like that!

File: project/ProjectSettings.scala [hunk 2]
```diff
@@ -58,6 +58,9 @@ object ProjectSettings {
       .withWarnScalaVersionEviction(false),
   )
 
+  def isCi = sys.env.get("CI").getOrElse("false") == "true"
```
Comment (rtyley) [inline project/ProjectSettings.scala:61]: I'm curious about this - where does `CI` get set to `true`? This is a new environment variable, is that right?

I don't see any environment variable being set in https://github.com/guardian/frontend/settings/variables/actions :

image

...I can't see where this `CI` variable would have come from?

Comment (rtyley) [reply project/ProjectSettings.scala:61]: Oh wow, that's amazing! I did not know about the standard `CI` env variable set by GitHub!

Comment (rtyley) [reply project/ProjectSettings.scala:61]: I've opened https://github.com/guardian/frontend/pull/27709 to put a tiny bit of logging on this - thank you very much for explaining it to me!
