### PR TITLE
Fix "Show more" on Football tag fixture pages

### LINKED ISSUE #25410: Football matches list doesn't preserve filters when pressing 'More'
On this [page](https://www.theguardian.com/football/premierleague/fixtures) you should only see Premier League matches, but when you clikc "More" at the bottom of the page it loads matches that aren't Premier League.

### PR DESCRIPTION
**Pull request by AshCorr**
## What does this change?

- Adds a new "Show more" endpoint which supports filtering fixtures by team or competition tag
- Updates link used by pagination button on a competition/team fixtures page to use the new endpoint
- Refactors fixtures controller to allow a bit more flexibility when fetching fixtures by tag

Fixes #25410

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

Taken from https://www.theguardian.com/football/premierleague/fixtures

| Before      | After      |
|-------------|------------|
| ![before][] | ![after][] |

[before]: https://user-images.githubusercontent.com/21217225/187669014-31952764-28fa-437b-92b9-86a668e741f2.gif
[after]: https://user-images.githubusercontent.com/21217225/187669074-edd4488c-a4bd-4f35-ba12-34a60d0dcc6b.gif

### CODE REVIEW

File: sport/app/football/controllers/FixturesController.scala [hunk 1]
```diff
@@ -52,53 +60,34 @@ class FixturesController(
...
-    }
-
-  private def renderTeamFixtures(teamName: String, team: FootballTeam, date: LocalDate): Action[AnyContent] =
-    Action { implicit request =>
-      val fixtures = TeamFixturesList(date, competitionsService.competitions, team.id)
-      val page = new FootballPage(s"football/$teamName/fixtures", "football", s"${team.name} fixtures")
-      renderMatchList(page, fixtures, filters)
-    }
-
-  def teamFixturesComponentJson(teamId: String): Action[AnyContent] = teamFixturesComponent(teamId)
```
Comment (AshCorr) [inline sport/app/football/controllers/FixturesController.scala:87]: I needed to update this method when refactoring `TeamFixturesList` but I noticed that these methods aren't referenced anywhere, not even in a routes file, so instead of updating them I've removed them.

**Review by OllysCoding — APPROVED** [review]
+1 Nice fix :)
