### PR TITLE
Fix football fixture json for dcr

### LINKED ISSUE #13212: Football Fixtures JSON Endpoint
See #13202 for an example.

### PR DESCRIPTION
**Pull request by marjisound**
## What is the value of this and can you measure success?

- Reviewed all `/football/fixtures` endpoints to assess what needed updating to support DCR JSON responses.
- Most endpoints were already compatible, but `/football/fixtures/more/` required an update, which has now been implemented.
- Updated `DotcomRenderingFootballDataModel` to include filters—these filters represent a list of relevant competitions for the league selector, determined based on match type and date.
- Fixed a bug in the `isOn` function, which was previously always returning false for any input.

### Note:
The fix for isOn will now enable the league selector on the /football/live page, which was previously missing.

### CODE REVIEW

File: sport/app/football/implicits/Football.scala [hunk 1]
```diff
@@ -44,8 +44,7 @@ trait Football {
       m.awayTeam.score,
     )
 
-    def isOn(date: LocalDate): Boolean =
-      m.date.toLocalDate.isAfter(date) && m.date.toLocalDate.isBefore(date.plusDays(1))
+    def isOn(date: LocalDate): Boolean = m.date.toLocalDate == date
```
Comment (andrewHEguardian) [inline sport/app/football/implicits/Football.scala:47]: This looks equivalent to me, but just wondering if there's some reason it was written that way

**Review by andrewHEguardian — APPROVED** [review]
Looks good 👍
