### PR TITLE
Reduce CPU & network consumption of Facia JSON download

### LINKED ISSUE #26335: "Too many operations in progress" in `FrontJsonFapi` fetching
There have been several recent incidents where the serving of fronts (eg https://www.theguardian.com/uk) to users became slow, and in fact failed.

There's a lot of things going on in these incidents, but in particular we do see these `TooManyOperationsInProgress ` errors in the [logs](https://logs.gutools.co.uk/s/dotcom/goto/5b477880-2586-11ee-a9e1-e75870600741):

```
Failed rendering world with concurrent.FutureSemaphore$TooManyOperationsInProgress: Too many operations in progress, 
cannot execute task
concurrent.FutureSemaphore$TooManyOperationsInProgress: Too many operations in progress, cannot execute task
	at concurrent.FutureSemaphore.execute(FutureSemaphore.scala:16)
	at services.fronts.FrontJsonFapi.parsePressedPage(FrontJsonFapi.scala:34)
	at services.fronts.FrontJsonFapi.$anonfun$pressedPageFromS3$2(FrontJsonFapi.scala:58)
```

image

- https://github.com/guardian/frontend/pull/18331 - 27th November 2017 : introduced `futureSemaphore`, limiting the number of concurrent operations to 10 per server
- https://github.com/guardian/frontend/pull/18359 - 30th November 2017 : introduced the use of `blockingOperations.executeBlocking` to `FrontJsonFapi` - non-async, thread-blocking code

### PR DESCRIPTION
**Pull request by rtyley**
This PR looks to fix https://github.com/guardian/frontend/issues/26335 by improving the scalability of Facia's pressed-page-json loading code in `FrontJsonFapi`. Originally it focussed only on adopting AWS SDK v2 to allow non-blocking async code for the downloading, but it now additionally includes a more significant change: **ETag-based caching**.

ETag caching is a pretty wonderful standard part of the HTTP protocol, relying on these 3 components:

* [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) HTTP response header - a hash of the content, returned by the server
* [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) HTTP request header - sent by the client, to indicate what content it already has, by sending its ETag
* [`304 Not Modified`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) HTTP response code - returned by a server when content is unchanged from the supplied ETag, with an otherwise blank response (no need to return a response!)

I've extracted the code needed for an `ETagCache` into a new library at https://github.com/guardian/etag-caching .

## ETag Caching Benefits

* Significant savings in terms of resources:
  * **Network**: `PressedPage`s are only re-downloaded if the S3 content has _changed_
  * **CPU**: Cached `PressedPage`s are only re-parsed if the S3 content has _changed_
* Retains the 'stay current' behaviour of the old, non-caching solution: S3 queried with every request to ensure the ETag is up-to-date.
* Also, given the cache is based on the ([S](https://github.com/blemale/scaffeine))[Caffeine](https://github.com/ben-manes/caffeine) caching library:
  * In-flight requests for a given key are unified, so 100 simultaneous requests for a key make just **1** fetch-and-parse 

The fetching and parsing code is also improved:

* Updated to AWS SDK v2, using non-blocking async code to avoid blocking threads while downloading the Facia JSON data from S3
* Directly transform bytes into JsValue, without constructing a `String` first

### Memory requirements of caching

Currently `facia` runs on [`c6g.2xlarge`](https://instances.vantage.sh/aws/ec2/c6g.2xlarge) instances (16GB RAM), with a JVM heap of 12GB. I'm going to suggest that it's reasonable for the `ETagCache` to consume up to 4GB of the 12GB RAM.

There are ~300 fronts, each of which can have [4 different variants](https://github.com/guardian/frontend/blob/f64c5b681f53a9c87ae1e76c529d08b3ad16ef6b/common/app/model/PressedPage.scala#L68-L86), so currently there could be up to 1200 different `PressedPage` objects. From [heapdump](https://drive.google.com/file/d/1yjfqLMpWqww6-3L8RBN0yrAf9hQHHpSC/view?usp=sharing) analysis, the largest `PressedPage` retains ~22MB of memory (most instances are smaller, averaging at 4MB). With the 4GB budget, and assuming a worse case of 22MB per `PressedPage`, we can afford to set a max size on the cache of ~180 entries. Although it's disappointing we can't hold _all_ of the `PressedPage`s, the [priorities of the eviction policy used by the Caffeine caching library](https://github.com/ben-manes/caffeine/wiki/Efficiency) should ensure that we get a good hit rate on the most in-demand fronts.

_Incidentally, heapdump analysis also shows that some structures within `PressedPage` are memory inefficient when considered from the perspective of holding many `PressedPage` objects in memory at once - using object pooling on `model.Tag` for instance, would probably lead to a 80% reduction of the total retained memory._

### Removal of `FutureSemaphore`

`FutureSemaphore`, introduced in November 2017 with https://github.com/guardian/frontend/pull/18331, is removed in this change - as described in https://github.com/guardian/frontend/issues/26335#issuecomment-1655868616 & https://github.com/guardian/frontend/pull/26336#issuecomment-1645645161, the late-stage 32-concurrent-decoding-processes limit was harmful: it led to work (JSON download & `String` generation) being thrown away, without the result of that work being cached by the CDN.

### Testing

Testing [total request-response time](https://everything.curl.dev/usingcurl/verbose/writeout#:~:text=time_total) on CODE:

```
$ ssm cmd -p frontend -t facia,frontend,code -c "curl -sS --head -w ',result,%{url_effective},%{time_total}\n' http://localhost:9000/uk | grep -e result -e Commit | tr -d '\r\n'" 2> /dev/null | grep Commit | cut -d' ' -f2 | cut -d',' -f1,3- | sort
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,0.883647
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,0.986826
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,1.013991
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,1.022075
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.626043
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.629217
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.645948
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.669940
```

### CODE REVIEW

**Comment by rtyley** [comment]
I've talked this through with @abeddow91, @arelra, @ioannakok, @georgeblahblah and @ParisaTork at the 2pm meeting today, and response was positive, no blocking objections!

Some evidence shared:

* During the meeting: with the CODE Facia ASG 50/50 split between 4 old instances on the main branch with 34d8b3ac2752dc35bae52240c82ebd48945a3408, and 4 new ones on eb1fdaeb1db72479be8b51e06351f905b72d479b, the new code demonstrated consistently faster response times on single requests to the `/uk` front:
```
$ ssm cmd -p frontend -t facia,frontend,code -c "curl -sS --head -w ',result,%{url_effective},%{time_total}\n' http://localhost:9000/uk | grep -e result -e Commit | tr -d '\r\n'" 2> /dev/null | grep Commit | cut -d' ' -f2 | cut -d',' -f1,3- | sort
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,0.883647
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,0.986826
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,1.013991
34d8b3ac2752dc35bae52240c82ebd48945a3408,http://localhost:9000/uk,1.022075
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.626043
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.629217
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.645948
eb1fdaeb1db72479be8b51e06351f905b72d479b,http://localhost:9000/uk,0.669940
```
* Captured prior to the meeting: Two snapshots of heap memory usage on a local instance of Frontend/DCR while testing with 50 concurrent requests to the `/uk` front:
  * Old code on `main`: heap rises quickly to 8GB/12GB, significant GC activity
image
  * This PR: heap never goes higher than 1.5GB, GC activity is not visible
image

**Comment by bryophyta** [comment]
> There are ~300 fronts, each of which can have [4 different variants](https://github.com/guardian/frontend/blob/f64c5b681f53a9c87ae1e76c529d08b3ad16ef6b/common/app/model/PressedPage.scala#L68-L86), so currently there could be up to 1200 different PressedPage objects

Thanks for the detailed write-up @rtyley! Not sure if this has come up already, but (iirc) the only reason @ioannakok and I were able to find for having a `lite` version, when we looked into it, was to save some parsing overhead. I haven't followed this PR in detail, but if the new caching strategy tips the balance significantly in favour of having fewer page objects in memory then that might offset the overhead from having to parse the 'full' version of the page json when it _is_ parsed.

Might be worth looking into if it hasn't been discussed yet?

**Comment by rtyley** [comment]
> @ioannakok and I were able to find for having a `lite` version, when we looked into it, was to save some parsing overhead.

Ah interesting - that would have been https://github.com/guardian/frontend/pull/18364 & https://github.com/guardian/frontend/pull/18365 ...

> I haven't followed this PR in detail, but if the new caching strategy tips the balance significantly in favour of having fewer page objects in memory then that might offset the overhead from having to parse the 'full' version of the page json when it _is_ parsed.

That is a super interesting point! Looking at the uncompressed files sizes for [`s3://aws-frontend-store/PROD/frontsapi/pressed/live/uk/fapi/`](https://s3.console.aws.amazon.com/s3/buckets/aws-frontend-store?region=eu-west-1&prefix=PROD/frontsapi/pressed/live/uk/fapi/&showversions=false):

```
5980936 pressed.v2.adfree.json
4025640 pressed.v2.lite.adfree.json

6063014 pressed.v2.json
4107718 pressed.v2.lite.json
```

...the lite versions _aren't even dramatically smaller_ - they are still 67% of the same size as the original versions of those files.

So I think you're right - they're adding 67% to storage requirements (assuming that the Scala case-class memory representation is roughly proportional to the file size) and are actively harmful to the cache hit rate, now that we're using a cache.

Subsequent to this PR, in a new PR, I definitely agree: **the 'lite' versions should be completely removed**. The only thing to watch out for would be to see if the output of the endpoints that _use_ the 'lite' versions (`renderFrontHeadline()`
`renderFrontPressResult()` & `renderFrontJsonMinimal()`) stays the same, depending whether they perform their own trimming that will work on the full versions of `PressedPage`, or if were relying on the trimmed nature of the 'lite' version at all.

**Comment by bryophyta** [comment]
Thanks for this!

> The only thing to watch out for would be to see if the output of the endpoints that use the 'lite' versions (renderFrontHeadline()
renderFrontPressResult() & renderFrontJsonMinimal()) stays the same, depending whether they perform their own trimming that will work on the full versions of PressedPage, or if were relying on the trimmed nature of the 'lite' version at all.

Agreed that we'd need to check implications for consumers 👍 _Hopefully_ it should be easy enough to repurpose the existing code that creates the `lite` versions in the current implementation, and run it when those endpoints are hit?

From what I remember though it might take a little bit of detective work to find out who the consumers are though (I happen to know that one of the consumers of `renderFrontJsonMinimal()` is the Pressreader lambdas, but that's only because by coincidence I've been working on those on my new team.)

But ultimately up to WebX to decide whether it's something to prioritise of course 🙂

File: common/app/services/fronts/FrontJsonFapi.scala [hunk 1]
```diff
@@ -1,70 +1,66 @@
...
-    errorLoggingF(s"FrontJsonFapi.pressedPageFromS3 $path") {
-      for {
-        s3FrontData <- loadPressedPageFromS3(path)
-        pressedPage <- parsePressedPage(s3FrontData)
-      } yield pressedPage
-    }
-
 }
 
-class FrontJsonFapiLive(val blockingOperations: BlockingOperations) extends FrontJsonFapi {
```
Comment (ioannakok) [inline common/app/services/fronts/FrontJsonFapi.scala:64]: Since we're deleting `BlockingOperations` [this config](https://github.com/guardian/frontend/blob/main/facia/conf/application.conf#L27-L32) can also go.

**Review by ioannakok — APPROVED** [review]
Fantastic work @rtyley 👏 Thank you for doing this and for the great PR write-up!

**Comment by mchv** [comment]
Excellent work @rtyley 💎

File: common/app/services/fronts/FrontJsonFapi.scala (hunk 1 above)
Comment (rtyley) [reply common/app/services/fronts/FrontJsonFapi.scala:64]: Ah, that bit of config is still used by the `BlockingOperations` class, and that hasn't been deleted (unfortunately?!) - we're no longer using it for the Fronts-JSON download code, but it's still used elsewhere, eg [`dfp.OrderAgent`](https://github.com/guardian/frontend/blob/08dabf7b8cb2ed8a53b249be9551ddf6407ff3b4/admin/app/dfp/OrderAgent.scala#L9).

**Comment by rtyley** [comment]
Thanks all! I'm looking to merge this today, and deploy it to PROD - I would like to pair with a WebX person on the release? Would be good to keep an eye on the graphs as it goes out.

**Review by sophie-macmillan — APPROVED** [review]

**Comment by rtyley** [comment]
So far, I would say this looks healthy overall, tho' two metrics are perturbing, need follow up.

### Good news

Average CPU utilisation in the EC2 ASG dropped when we deployed this PR - and rose when we halved the number of instances from 6 to 3 - but it did not quite double 👍  ([graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount~visible~false))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount~visible~false))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'front-download-latency~'.~'.~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'2023-08-09T08*3a00*3a00.000Z~end~'2023-08-09T16*3a00*3a00.000Z~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2326338*20deployed~value~'2023-08-09T11*3a09*3a00.000Z)~(label~'ASG*20reduced*20from*206*20to*203~value~'2023-08-09T14*3a20*3a00.000Z))))&query=~'*7bAWS*2fEC2*2cAutoScalingGroupName*7d*201AZBJHR7UVRVD)):

image


More than half of S3 requests are now receiving `NOT MODIFIED` - and this proportion even raised slightly as we halved the number of instances from 6 to 3 ([graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900~visible~false))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'front-download-latency~'.~'.~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'2023-08-09T08*3a00*3a00.000Z~end~'2023-08-09T16*3a00*3a00.000Z~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2326338*20deployed~value~'2023-08-09T11*3a09*3a00.000Z)~(label~'ASG*20reduced*20from*206*20to*203~value~'2023-08-09T14*3a20*3a00.000Z))))&query=~'*7bAWS*2fEC2*2cAutoScalingGroupName*7d*201AZBJHR7UVRVD)):


image

Decoding the bytes to `PressedPage`s is now slightly faster - that, I can't quite explain! ([graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount~visible~false))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount~visible~false))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900~visible~false))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(period~900))~(~'.~'front-download-latency~'.~'.~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'2023-08-09T08*3a00*3a00.000Z~end~'2023-08-09T16*3a00*3a00.000Z~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2326338*20deployed~value~'2023-08-09T11*3a09*3a00.000Z)~(label~'ASG*20reduced*20from*206*20to*203~value~'2023-08-09T14*3a20*3a00.000Z))))&query=~'*7bAWS*2fEC2*2cAutoScalingGroupName*7d*201AZBJHR7UVRVD)):

image

### Concerning metrics

#### Download time

Despite more than half of them being empty `NOT MODIFIED` responses, the overall average download time has _risen_ ([graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount~visible~false))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount~visible~false))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900~visible~false))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(period~900~visible~false))~(~'.~'front-download-latency~'.~'.~'.~'.))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'2023-08-09T08*3a00*3a00.000Z~end~'2023-08-09T16*3a00*3a00.000Z~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2326338*20deployed~value~'2023-08-09T11*3a09*3a00.000Z)~(label~'ASG*20reduced*20from*206*20to*203~value~'2023-08-09T14*3a20*3a00.000Z))))&query=~'*7bAWS*2fEC2*2cAutoScalingGroupName*7d*201AZBJHR7UVRVD)):

image

I can't easily explain this - I feel like either AWS SDK v2 is actually somehow slower than v1, or possibly the fact that we're using async and need to wait for a thread to process the result of the response?!

#### Garbage collection

Garbage collections have increased ([graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD)~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount~visible~false))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount~visible~false))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900~visible~false))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(period~900~visible~false))~(~'.~'front-download-latency~'.~'.~'.~'.~(visible~false)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'2023-08-09T08*3a00*3a00.000Z~end~'2023-08-09T16*3a00*3a00.000Z~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2326338*20deployed~value~'2023-08-09T11*3a09*3a00.000Z)~(label~'ASG*20reduced*20from*206*20to*203~value~'2023-08-09T14*3a20*3a00.000Z))))&query=~'*7bAWS*2fEC2*2cAutoScalingGroupName*7d*201AZBJHR7UVRVD)) - this is kind of what you'd expect when you hold more objects in memory, but still not very nice to see. I think the main problem here is that the cache max size (180) is pretty small, and so this leads to quite a lot of cache thrashing- if we could hold more `PressedPage`s in memory, we would see _less_ garbage collection.

image

I feel like a lot of this bad stuff can be addressed by reducing the memory footprint of a `PressedPage` -something for a subsequent PR.
